/*
 * Antonin Harok HAR0199
 *
 * File: Scene.cpp
 * Description:  Implementation file for the Scene class
 */

#include "Scene.h"
#include "DrawableObject.h"
#include "Model.h"
#include "Shader.h"
#include "ShaderProgram.h"

#include <glad/gl.h>
#include <iterator>

#include "Models/sphere.h"
#include "Models/suzi_smooth.h"
#include "Models/login.h"
#include "Models/tree.h"
#include "Models/bushes.h"

Scene::Scene() = default;

Scene::~Scene() = default;

void Scene::createShaders()
{
	// Index 0: Red 
    Shader sphereVertexShader(GL_VERTEX_SHADER, "shaders/basic.vert");
    Shader sphereFragmentShader(GL_FRAGMENT_SHADER, "shaders/red.frag");
    shaderPrograms_.push_back(std::make_unique<ShaderProgram>(
        std::move(sphereVertexShader), std::move(sphereFragmentShader)));

    // Index 1: Blue 
    Shader suziVertexShader(GL_VERTEX_SHADER, "shaders/basic.vert");
    Shader suziFragmentShader(GL_FRAGMENT_SHADER, "shaders/blue.frag");
    shaderPrograms_.push_back(std::make_unique<ShaderProgram>(
        std::move(suziVertexShader), std::move(suziFragmentShader)));

	// Index 2: rainbow (basic colors from vertices for triangle and square)
    Shader rainbowVertexShader(GL_VERTEX_SHADER, "shaders/basic.vert");
    Shader rainbowFragmentShader(GL_FRAGMENT_SHADER, "shaders/basic.frag");
    shaderPrograms_.push_back(std::make_unique<ShaderProgram>(
        std::move(rainbowVertexShader), std::move(rainbowFragmentShader)));
}

void Scene::createModels(int mode)
{
	if(mode == 1)
	{
		// 1. triangle with vertex colors
		std::vector<float> triangleData = {
			0.0f, 0.5f, 0.0f, 1.0f, 0.0f, 0.0f,
			0.5f, -0.5f, 0.0f, 0.0f, 1.0f, 0.0f,
			-0.5f, -0.5f, 0.0f, 0.0f, 0.0f, 1.0f
		};
		static Model triangleModel(triangleData, 3, GL_TRIANGLES);
		drawableObjects_.push_back(std::make_unique<DrawableObject>(*shaderPrograms_[2], triangleModel));

		signature();
	}
	else if(mode == 2)
	{
		if (shaderPrograms_.empty()) //sphere
			return;

		static std::vector<float> sphereData(sphere, sphere + sizeof(sphere) / sizeof(float));
		static Model sphereModel(sphereData, static_cast<int>(sphereData.size() / 6), GL_TRIANGLES);

		auto sphereObject = std::make_unique<DrawableObject>(*shaderPrograms_[0], sphereModel);
		sphereObject->setTranslation(glm::vec3(0.0f, 0.0f, 0.0f));
		sphereObject->setScale(glm::vec3(0.5f));
		drawableObjects_.push_back(std::move(sphereObject));

		signature();
	}
	else if(mode == 3)
	{
		//---------------------------------------------------------------------------
		// ------------ Trees and bushes's grid pattern generated by AI -------------
		// scene with trees, bushes and sun 
		static std::vector<float> treeData(tree, tree + sizeof(tree) / sizeof(float));
		static std::vector<float> bushData(bushes, bushes + sizeof(bushes) / sizeof(float));
		static std::vector<float> sphereData(sphere, sphere + sizeof(sphere) / sizeof(float));
		static Model treeModel(treeData, static_cast<int>(treeData.size() / 6), GL_TRIANGLES);
		static Model bushModel(bushData, static_cast<int>(bushData.size() / 6), GL_TRIANGLES);
		static Model sunModel(sphereData, static_cast<int>(sphereData.size() / 6), GL_TRIANGLES);

		for (int i = 0; i < 12; ++i)
		{
			auto tree = std::make_unique<DrawableObject>(*shaderPrograms_[1], treeModel);
			tree->setTranslation(glm::vec3(-0.8f + (i % 4) * 0.45f, 0.2f - (i / 4) * 0.4f, 0.0f));
			tree->setScale(glm::vec3(0.07f));
			drawableObjects_.push_back(std::move(tree));
		}
		for (int i = 0; i < 12; ++i)
		{
			auto bush = std::make_unique<DrawableObject>(*shaderPrograms_[0], bushModel);
			bush->setTranslation(glm::vec3(-0.6f + (i % 4) * 0.45f, 0.1f - (i / 4) * 0.4f, 0.0f));
			bush->setScale(glm::vec3(0.12f));
			drawableObjects_.push_back(std::move(bush));
		}

		//---------------------------------------------------------------------------
		//---------------------------------------------------------------------------

		auto sun = std::make_unique<DrawableObject>(*shaderPrograms_[0], sunModel);
		sun->setTranslation(glm::vec3(0.75f, 0.7f, 0.0f));
		sun->setScale(glm::vec3(0.12f));
		drawableObjects_.push_back(std::move(sun));

		signature();

	}
	else if (mode == 4) //login
	{
		static std::vector<float> LoginData(login, login + sizeof(login) / sizeof(float));
		static Model LoginModel(LoginData, static_cast<int>(LoginData.size() / 6), GL_TRIANGLES);

		auto LoginObject = std::make_unique<DrawableObject>(*shaderPrograms_[1], LoginModel);
		LoginObject->setTranslation(glm::vec3(0.0f, 0.0f, 0.0f));
		drawableObjects_.push_back(std::move(LoginObject));
	}
	else if (mode == 5) 
	{
		// square with 4th vextex color (yellow) and using GL_TRIANGLE_STRIP
		std::vector<float> squareData = {
			-0.5f,  0.5f, 0.0f,   1.0f, 0.0f, 0.0f, //   1
			-0.5f, -0.5f, 0.0f,   0.0f, 1.0f, 0.0f, //   2
			0.5f,  0.5f, 0.0f,   0.0f, 0.0f, 1.0f, //  3
			0.5f, -0.5f, 0.0f,   1.0f, 1.0f, 0.0f  //             4 
		};
		static Model squareModel(squareData, 4, GL_TRIANGLE_STRIP);
		drawableObjects_.push_back(std::make_unique<DrawableObject>(*shaderPrograms_[2], squareModel));
		signature();
	}
	else if (mode == 6)
	{
		if (shaderPrograms_.size() < 2) //suzi
			return;

		std::vector<float> suziData(suziSmooth, suziSmooth + sizeof(suziSmooth) / sizeof(float));
		static Model suziModel(suziData, static_cast<int>(suziData.size() / 6), GL_TRIANGLES);

		auto suziObject = std::make_unique<DrawableObject>(*shaderPrograms_[1], suziModel);
		suziObject->setTranslation(glm::vec3(0.0f, 0.0f, 0.0f));
		drawableObjects_.push_back(std::move(suziObject));
		signature();
	}
}

void Scene::signature()
{
	static std::vector<float> LoginData(login, login + sizeof(login) / sizeof(float));
	static Model LoginModel(LoginData, static_cast<int>(LoginData.size() / 6), GL_TRIANGLES);

	auto LoginObject = std::make_unique<DrawableObject>(*shaderPrograms_[1], LoginModel);
	LoginObject->setTranslation(glm::vec3(0.5f, -0.8f, 0.0f));
	LoginObject->setScale(glm::vec3(0.1f));
	drawableObjects_.push_back(std::move(LoginObject));
}

void Scene::clearModels()
{
	drawableObjects_.clear();
}


void Scene::update()
{
    for (auto& obj : drawableObjects_)
        obj->update();
}

void Scene::setRotationDirection(int direction)
{
    for (auto& obj : drawableObjects_)
        obj->setRotationDirection(direction);
}

void Scene::render()
{
	for (auto& obj : drawableObjects_)
    {
		obj->draw();
    }
}